export const STORE_USER = "STORE_USER";
export const BEGIN_USER_AUTHENTIFICATION = "BEGIN_USER_AUTHENTIFICATION";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const AN_ERROR_OCCURED_DURING_LOGIN = "AN_ERROR_OCCURED_DURING_LOGIN";
export const RESET_WRONG_CREDENTIALS = "RESET_WRONG_CREDENTIALS";
export const WRONG_LOGIN_CREDENTIALS = "WRONG_LOGIN_CREDENTIALS";

export const STORE_ADMIN = "STORE_ADMIN";
export const STORE_OFFICE_ADMINISTRATOR = "STORE_OFFICE_ADMINISTRATOR";

export const LOGOUT = "LOGOUT";
export const AN_ERROR_OCCURED_DURING_LOGOUT = "AN_ERROR_OCCURED_DURING_LOGOUT";