
export const IDLE_TIMEOUT = 1000 * 60;
export const DEBOUNCE = 250;

export const DISPLAY_USER_MANAGEMENT_PAGE = "DISPLAY_USER_MANAGEMENT_PAGE";
export const DISPLAY_USER_REGISTRATION_PAGE = "DISPLAY_USER_REGISTRATION_PAGE";

export const DISPLAY_ADMINISTRATOR_REGISTRATION = "DISPLAY_ADMINISTRATOR_REGISTRATION";
export const DISPLAY_ADMINISTRATOR_MANAGEMENT = "DISPLAY_ADMINISTRATOR_MANAGEMENT";

export const DISPLAY_COMPANY_REGISTRATION_PAGE = "DISPLAY_COMPANY_REGISTRATION_PAGE";

export const DISPLAY_TEAMS = "DISPLAY_TEAMS";

export const DISPLAY_PROJECTS = "DISPLAY_PROJECTS";
export const DISPLAY_TEAM_MEMBERS = "DISPLAY_TEAM_MEMBERS";

export const DISPLAY_OBJECTIVES = "DISPLAY_OBJECTIVES";
export const DISPLAY_PROJECT_OBJECTIVE = "DISPLAY_PROJECT_OBJECTIVE";

export const DISPLAY_SYSTEM_ADMIN_REGISTRATION = "DISPLAY_SYSTEM_ADMIN_REGISTRATION";
export const DISPLAY_SYSTEM_ADMIN_MANAGEMENT = "DISPLAY_SYSTEM_ADMIN_MANAGEMENT";





